### ISSUE TITLE
DataStage is missing from Cloud Pak for Data as a Service documentation

### ISSUE THREAD

**Issue by merideeG1t** [ibm-cloud-docs/cloud-pak-data#7]

**Comment by patsmith-public** [comment]
I'm not sure this issue is valid. DataStage is in[ Cloud Pak for Data](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=services-datastage) and also [Cloud Pak for Data as a Service](https://dataplatform.cloud.ibm.com/docs/content/svc-welcome/datastage.html?context=cpdaas&audience=wdp) documentation.
