### ISSUE TITLE
Cloud pak for data with Satellite

### ISSUE THREAD

**Issue by lanoue77** [ibm-cloud-docs/cloud-pak-data#8]
Do you have any intention to add documentation on how to install Cloud Pak on a Satellite location?

**Comment by ARingis** [comment]
Hi @lanoue77! We've followed up to get this documented. One of the SMEs that we talked to said that the install instructions for Cloud Pak for Data are the same for any location where you install it. However, these locations need to be configured before you can install Cloud Pak for Data.

For a satellite location, you can either install Red Hat OpenShift and then install Cloud Pak for Data. Or you can install Cloud Pak for Data without Openshift.

With that in mind, we updated [step 2 in this topic](https://test.cloud.ibm.com/docs-draft/cloud-pak-data?topic=cloud-pak-data-getting-started) to mention that installing on a satellite location is an option. And it links to documentation for satellite on [supported services on satellite locations](https://cloud.ibm.com/docs/satellite?topic=satellite-managed-services).

**Comment by lanoue77** [comment]
Hi @ARingis! Thank for the feedback. However when I follow the instruction in this [link](https://cloud.ibm.com/docs/satellite?topic=satellite-managed-services) I can't find Cloud Pak for Data as a source service. Shoud I open an issue in ibm-cloud-docs/satellite?
![image](https://github.com/ibm-cloud-docs/cloud-pak-data/assets/30326433/915c41e6-9289-43c5-bf6c-b5be10e83b00)
EDIT:  When I chose a service that is part of Cloud Pak for Data like watsonx.governance, I don't see Satellite as a target service

**Comment by ARingis** [comment]
Hi @lanoue77! I'll follow up with the SME again. He made it sound like [the steps here](https://test.cloud.ibm.com/docs-draft/cloud-pak-data?topic=cloud-pak-data-getting-started#assign_license) were the ones to follow. But I'll mention your issues and see if he can clarify.

Either way, I'll try to get an answer as soon as I can! I'm sorry the steps above didn't work.

**Comment by ARingis** [comment]
Hi @lanoue77. I heard back from the SME, and he just wants to check a few things. Which version of cpd do you want to install?

**Comment by lanoue77** [comment]
I am currently trying to install the 4.8.2 version

**Comment by ARingis** [comment]
Sorry for the delay. I heard back from the SME, and he suggested following the [steps for CPD](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x). He said that it should work as long as you choose the CPD version that you are want to install.

I checked through some of the content to see if I could find something more specific. There are these instructions here: 

- [Installing Cloud Pak for Data](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=installing)
- [Cloud deployment environments](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=planning-cloud-deployment-environments#deployment-environments__manual)

In this case I think Red Hat Openshift can be installed on an IBM Cloud Satellite, and then CPD installed after that. In this case, I don't think it is the cloud version of CPD.

I can try to get more details from the SME. But I thought I would mention the high-level steps to at least give you an update.

**Comment by lanoue77** [comment]
I have installed it by following those steps. But would it be possible to add information about satellite in the docs?
And is there a plan to add the installation of CP4D on a satellite like other services, web-interface like openshift.

I ask because it is listed in the Featured services of [IBM Cloud Satellite](https://www.ibm.com/products/satellite?utm_content=SRCWW&p1=Search&p4=43700056326614894&p5=e&gad_source=1&gclid=EAIaIQobChMIpdqyr-jkhAMV62NHAR1Y4QHVEAAYASAAEgLUQfD_BwE&gclsrc=aw.ds) and the other services can be installed by interface

**Comment by ARingis** [comment]
Great! I'm glad it worked. Yes, I'll look into updating the docs so that anyone using satellite can figure out what they need to do more easily.

I don't really know if there is a plan to add a feature allowing CP4D to be installed on satellite using a web-interface. I'll try following up with someone who is more familiar with the plans for CP4D development to get an answer.

**Comment by ARingis** [comment]
Hi @lanoue77 I followed up with a few people. From the sound of it, it does not sound like there is an existing plan to add the installation of CP4D on a satellite location like other services. Or at best, it is not one of their highest priorities. However, one person noted that if there are enough requests for this feature, it could become more of a priority.

I'm following up with marketing so see if we can change the [IBM Cloud Satellite](https://www.ibm.com/products/satellite?utm_content=SRCWW&p1=Search&p4=43700056326614894&p5=e&gad_source=1&gclid=EAIaIQobChMIpdqyr-jkhAMV62NHAR1Y4QHVEAAYASAAEgLUQfD_BwE&gclsrc=aw.ds) page so that what can be installed is clearer.
